export const mainBarLinks = [
  {
    iconURL: '/assets/chats.svg',
    route: '/',
    label: 'Chats',
  },
  {
    iconURL: '/assets/updates.svg',
    route: '/updates',
    label: 'Updates',
  },
  {
    iconURL: '/assets/communities.svg',
    route: '/communities',
    label: 'Communities',
  },
  {
    iconURL: '/assets/calls.svg',
    route: '/calls',
    label: 'Calls',
  },
];

export const chats = [
  {
    id: '1',
    name: 'John Doe',
    lastMessage: 'Hey, how are you? Hey, how are you? Hey, how are you?',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T12:00:00Z',
  },
  {
    id: '2',
    name: 'Jane Smith',
    lastMessage: 'Are we still on for tomorrow?',
    messages: [
      { fromMe: false, text: 'Hey there!' },
      { fromMe: true, text: 'Hi!' },
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
      { fromMe: false, text: 'Hey there!' },
      { fromMe: true, text: 'Hi!' },
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
      { fromMe: false, text: 'Hey there!' },
      { fromMe: true, text: 'Hi!' },
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
      { fromMe: false, text: 'Hey there!' },
      { fromMe: true, text: 'Hi!' },
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
      { fromMe: false, text: 'Hey there!' },
      { fromMe: true, text: 'Hi!' },
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
      { fromMe: false, text: 'Hey there!' },
      { fromMe: true, text: 'Hi!' },
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T12:05:00Z',
  },
  {
    id: '3',
    name: 'Alice Johnson',
    lastMessage: 'Can you send me the report?',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T12:10:00Z',
  },
  {
    id: '4',
    name: 'Bob Brown',
    lastMessage: 'Let’s catch up later.',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T12:15:00Z',
  },
  {
    id: '5',
    name: 'Charlie Davis',
    lastMessage: 'Got it, thanks!',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T12:20:00Z',
  },
  {
    id: '6',
    name: 'David Wilson',
    lastMessage: 'See you at the meeting.',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T12:25:00Z',
  },
  {
    id: '7',
    name: 'Eva Green',
    lastMessage: 'I’ll call you later.',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T12:30:00Z',
  },
  {
    id: '8',
    name: 'Frank White',
    lastMessage: 'Let’s discuss this next week.',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T12:35:00Z',
  },
  {
    id: '9',
    name: 'Grace Black',
    lastMessage: 'Thanks for the update!',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T12:40:00Z',
  },
  {
    id: '10',
    name: 'Hank Grey',
    lastMessage: 'I’ll send you the details soon.',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T12:45:00Z',
  },
  {
    id: '11',
    name: 'Ivy Blue',
    lastMessage: 'Can we reschedule our meeting?',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T12:50:00Z',
  },
  {
    id: '12',
    name: 'Jack Red',
    lastMessage: 'Looking forward to your reply.',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T12:55:00Z',
  },
  {
    id: '13',
    name: 'Kathy Yellow',
    lastMessage: 'I’ll be there in 10 minutes.',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T13:00:00Z',
  },
  {
    id: '14',
    name: 'Leo Purple',
    lastMessage: 'Can you help me with this issue?',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T13:05:00Z',
  },
  {
    id: '15',
    name: 'Mia Orange',
    lastMessage: 'Great job on the presentation!',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T13:10:00Z',
  },
  {
    id: '16',
    name: 'Nina Pink',
    lastMessage: 'Let’s finalize the details tomorrow.',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T13:15:00Z',
  },
  {
    id: '17',
    name: 'Oscar Cyan',
    lastMessage: 'I’ll check my schedule and get back to you.',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T13:20:00Z',
  },
  {
    id: '18',
    name: 'Paul Magenta',
    lastMessage: 'Thanks for your help!',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T13:25:00Z',
  },
  {
    id: '19',
    name: 'Quinn Brown',
    lastMessage: 'Can we talk about this later?',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T13:30:00Z',
  },
  {
    id: '20',
    name: 'Rita White',
    lastMessage: 'I’ll send you the files shortly.',
    messages: [
      { fromMe: true, text: 'Hey there!' },
      { fromMe: false, text: 'Hi!' },
      { fromMe: true, text: 'How have you been?' },
      { fromMe: false, text: 'I am good, thanks!' },
    ],
    timestamp: '2023-10-01T13:35:00Z',
  },
];
